name       : dunst
version    : 1.7.3
release    : 9
source     :
    - https://github.com/dunst-project/dunst/archive/refs/tags/v1.7.3.tar.gz : 150c782690286e163663b0eb2605b733927240159738b8365808b851e0afbbee
license    : BSD-3-Clause
homepage   : https://dunst-project.org
component  : desktop.i3
summary    : Customizable and lightweight notification-daemon.
description: |
    Dunst is a lightweight replacement for the notification-daemons provided by most desktop environments. It's very customizable, doesn't depend on any toolkits and therefore fits in those windowmanager centric setups we all love to customize to perfection.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(dbus-1)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(libnotify)
    - pkgconfig(pango)
    - pkgconfig(wayland-server)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
build      : |
    %make PREFIX=/usr SYSCONFDIR=/usr/share
install    : |
    %make_install PREFIX=/usr SYSCONFDIR=/usr/share
