name       : dunst
version    : 1.2.0
release    : 3
source     :
    - https://github.com/dunst-project/dunst/archive/v1.2.0.tar.gz : a3c05b5ef87e88704a6207236e42773dfbcf50cb23c7cf51e494a7236b75c5ad
license    : BSD
component  : desktop.i3
summary    : Customizable and lightweight notification-daemon.
description: |
    Dunst is a lightweight replacement for the notification-daemons provided by most desktop environments. It's very customizable, doesn't depend on any toolkits and therefore fits in those windowmanager centric setups we all love to customize to perfection.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(dbus-1)
    - pkgconfig(libxdg-basedir)
    - pkgconfig(pango)
    - pkgconfig(xinerama)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xrandr)
    - pkgconfig(gtk+-2.0)
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
