name       : dunst
version    : 1.6.1
release    : 8
source     :
    - https://github.com/dunst-project/dunst/archive/refs/tags/v1.6.1.tar.gz : cc7d801575f75e92b18d46ee5d3df80aaf331c88b83ec6caabbecf8636310e13
license    : BSD
component  : desktop.i3
summary    : Customizable and lightweight notification-daemon.
description: |
    Dunst is a lightweight replacement for the notification-daemons provided by most desktop environments. It's very customizable, doesn't depend on any toolkits and therefore fits in those windowmanager centric setups we all love to customize to perfection.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(dbus-1)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(libnotify)
    - pkgconfig(pango)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
build      : |
    %make PREFIX=/usr SYSCONFDIR=/usr/share WAYLAND=0
install    : |
    %make_install PREFIX=/usr SYSCONFDIR=/usr/share WAYLAND=0