name       : dunst
version    : 1.1.0
release    : 2
source     :
    - http://knopwob.org/public/dunst-release/dunst-1.1.0.tar.bz2 : c72bf167eaab4e44a98ec87101b023efee0aa8916df56630b99a5bc53f8d7070
license    : BSD 
component  : desktop.i3
summary    : Customizable and lightweight notification-daemon.
description: |
    Dunst is a lightweight replacement for the notification-daemons provided by most desktop environments. It's very customizable, doesn't depend on any toolkits and therefore fits in those windowmanager centric setups we all love to customize to perfection.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(dbus-1)
    - pkgconfig(libxdg-basedir)
    - pkgconfig(pango)
    - pkgconfig(xft)
    - pkgconfig(xinerama)
    - pkgconfig(xscrnsaver) 
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
